-- GENERATED by certkit/emit_bounded_decide.py — emit_p647_bounded(1000, "native_decide", "p647_bounded_native").
-- W2 golden cert: native_decide SCALE variant. B = 1000 (20× the pure cert's B=50).
-- B was tuned DOWN from the spec's nominal 5000: native_decide must still clear the
-- `erdos lean check` 120s native-compile gate, and B=5000 timed out at 120s (tau does
-- an O(m) divisor scan per m, so witnessExists n is O(n²), summed over all n). B=2000
-- also grazed the limit (~115s); B=1000 clears comfortably (~14s).
-- Axioms DELIBERATELY include Lean.ofReduceBool (+ Lean.trustCompiler) — the explicit
-- trust delta vs. the pure-`decide` cert (P647Bounded.lean, B=50), which depends on NO
-- axioms at all. Same statement shape, larger B, traded for compiled-evaluator trust.
-- Erdős #647 (bounded): for 24 < n ≤ 1000, max_{m<n}(m+τ(m)) > n+2.
-- τ(m) = number of divisors, defined here (no mathlib).
def tau (m : Nat) : Nat :=
  ((List.range (m+1)).filter (fun d => d != 0 && m % d == 0)).length

def witnessExists (n : Nat) : Bool :=
  (List.range n).any (fun m => decide (n + 3 ≤ m + tau m))

theorem p647_bounded_native : ∀ n, n < 1001 → 24 < n → witnessExists n = true := by native_decide

#print axioms p647_bounded_native
