-- GENERATED by certkit/emit_bounded_decide.py  —  emit_p647_bounded(50, "decide").
-- W2 golden cert: pure-`decide` variant. B = 50 (largest tested; pure kernel `decide`
-- cleared B=50 in ~1s, so no down-tuning was needed). Axioms: NONE (not even propext,
-- and crucially NO Lean.ofReduceBool) — the witness-pure trust baseline. The
-- native_decide scale variant (P647BoundedNative.lean, B=1000) adds ofReduceBool:
-- that delta is the entire point of this pair.
-- Erdős #647 (bounded): for 24 < n ≤ 50, max_{m<n}(m+τ(m)) > n+2.
-- τ(m) = number of divisors, defined here (no mathlib).
def tau (m : Nat) : Nat :=
  ((List.range (m+1)).filter (fun d => d != 0 && m % d == 0)).length

def witnessExists (n : Nat) : Bool :=
  (List.range n).any (fun m => decide (n + 3 ≤ m + tau m))

theorem p647_bounded : ∀ n, n < 51 → 24 < n → witnessExists n = true := by decide

#print axioms p647_bounded
